name: Build EXE

on:
  push:
    branches:
      - main
      - "bugfix_exe*" # Matches branches like bugfix_exe_dates, bugfix_exe/feature-x, etc.

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pyinstaller==6.12.0
          pip install -e .

      - name: Generate version info
        run: python generate_version.py

      - name: Build EXE using spec file
        run: pyinstaller --clean --noconfirm islandr.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: islandr-windows
          path: dist/islandr/
